FORMAT: 1A
HOST: http://pwajg-server.herokuapp.com/apiv1/

# pwajg-server

Simple Node js server for Discussion board.

## API authentication [/auth]

### Generate new AUTH token. [POST]

Providing `login` and `password` of existing user returns authentication token for comunication with API. Returned token must by provided in `Auth` header with each subsequent request, otherwise you get back 401 Unauthorized status code.

+ Request

+ Parameters
    + login: (string) - User login, preferably his email.
    + password: (string) - The oAuth client ID

+ Response 200 (application/json)
        {
            "token": "ac4cb54caac5bca7ef455",
        }

+ Response 404 (application/json)
        {
            "message": "Sorry, bad login or password.",
        }

### Prolong token validity [PUT]

This call prolongs your token validity by 30 minutes.

+ Request
    + Headers

        Auth: {token}

+ Response 200 (application/json)
        {
            "message": "Token prolonged.",
        }

### Invalidate current token. [DELETE]

+ Request
    + Headers

        Auth: {token}

+ Response 200 (application/json)
        {
            "message": "Token deleted.",
        }
