FORMAT: 1A
HOST: http://pwajg-server.herokuapp.com/apiv1/

# pwajg-server

Simple Node js server for Discussion board.

# Group Authentication

## API token authentication [/auth]

### Generate new token. [POST]

Providing `login` and `password` of existing user returns authentication token for comunication with API. Returned token must by provided in `Auth` header with each subsequent request, otherwise you get back **401 Unauthorized** status code.
+ Request

        {
            "login": "login",
            "password": "password"
        }

+ Response 200 (application/json)

        {
            "token": "ac4cb54caac5bca7ef455",
        }

+ Response 404 (application/json)

### Prolong token validity [PUT]

This call prolongs your token validity by 30 minutes. Note that every call with token prolongs token validity. This could be used to keep token alive by calling this resource on background.

+ Request
    + Headers

            Auth: {token}

+ Response 200 (application/json)

### Invalidate current token. [DELETE]

+ Request
    + Headers

            Auth: {token}

+ Response 200 (application/json)

### Get current user id. [GET]

+ Request
    + Headers

            Auth: {token}

+ Response 200 (application/json)

        {
            "user_id": "id",
        }
        
# Group User

## User details [/users/{user_id}]

+ Parameters
    + user_id (number) - User identificator

### Get user by id. [GET]

+ Request
    + Headers

            Auth: {token}


+ Response 200 (application/json)

        {
            "user_id": "id",
            "login": "login"
        }
        
+ Response 404 (application/json)

# Group Threds

## Threds management [/threads]

# Group Posts

## Posts management [/posts]
